# Generated by Django 2.2 on 2019-06-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name_plural': 'Pessoas'},
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='fk_equipe',
            new_name='equipe',
        ),
        migrations.AlterField(
            model_name='equipe',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateTimeField(),
        ),
    ]
